config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#top'
  get 'home/about'
  namespace :blogs do 
    resources :searches, only: :index, defaults: { format: :json }
  end

  resources :messages
  resources :users, only: [:index, :show, :edit, :update]
  resources :blogs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable

  has_many :blogs, dependent: :destroy
  attachment :profile_image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, only: [:edit, :update, :destroy]
  
  def after_sign_up_path_for(resource)
    user_path(resource)
  end

  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/blogs/searches_controller.rb
class Messages::SearchesController < ApplicationController
  def index
    @blogs = Blog.where('title LIKE(?)', "%#{params[:title]}%")

    respond_to do |format|
      format.html { redirect_to :root }
      # ↓検索結果のデータをレスポンスするコード
      format.json { render json: @blogs }
    end
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :authenticate_user!

  def new
    @blog = Blog.new
  end

  def create
    @blog = Blog.new(blog_params)
    @blog.user_id = current_user.id
    if @blog.save
      redirect_to blog_path(@blog.id)
    else 
      render "new"
    end
  end

  def index
    @blogs = Blog.all
    @user = current_user
  end

  def show
    @blog = Blog.find(params[:id])
    @user = @blog.user
  end



  def destroy
    blog = Blog.find(params[:id])
    blog.destroy
    redirect_to user_path(current_user.id)
  end


  private
  def blog_params
    params.require(:blog).permit(:title, :text)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
    

  def index
    @users = User.all
    @user = current_user
  end

  def show
    @user = User.find(params[:id])
    @blogs = @user.blogs
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render "edit"
    else
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
    redirect_to user_path(@user)
    flash[:notice] = "You have updated user successfully"
    else
    render action: :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction )
  end

  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/_blog.html.erb
<li class="blog"><%= link_to blog.title, blog %></li>

app/views/blogs/index.html.erb
<%= render 'users/profile', user: @user, blog: @blog %>
<div class="col-xs-9">
  <h1>Coroぷり日記一覧</h1>
<div class="contents">
  <%= text_field_tag :title,'', class: 'js-text_field', placeholder: 'タイトルを入力してください' %>
<ul class="js-blogs">
    <%= render @blogs %><!-- 部分テンプレートを呼び出し-->
  </ul>

</div>

app/views/blogs/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-8 col-xs-2">

      <h1>新規投稿</h1>

      <%= form_with model: @blog, local: true do |f| %>
        <div class="form-group"></div>
          <%= f.label :title %><br>
          <%= f.text_field :title, size: "70x10" %>
        </div>
        <div class="form-group">
          <%= f.text_area :text, size: "80x30", placeholder: "Coroぷりなこと書いてみよう♡" %>
          <%= f.submit %>
        </div>
      <% end %>
    </div>
    <i class="fas fa-arrow-circle-left"></i>
    <%= link_to "Cancel", blogs_path %>
  </div>
</div>

app/views/blogs/show.html.erb
<div class="container">
  <div class="row">
    <h2><%= @user.name %></h2>
    <div class="col-xs-10 offset-xs-1">
      <table class="table position-relative">
          <thead>
            <tr>
              <th class="col-xs-5">title</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><%= @blog.title %></td>
              <td><%= @blog.text %></td>
              <% if @user.id == current_user.id %>
              <td><%= link_to 'Destroy', blog_path(@blog.id), method: :delete, data: { confirm: "Are you sure？"}, class:"btn btn-danger" %></td>
              <% end %>
            </tr>
          </tbody>
        </table>
    </div>
  </div>
  <i class="fas fa-arrow-circle-left"></i>
  <%= link_to "back", blogs_path %>
</div>

app/views/home/about.html.erb
<h1>youkoso</h1>

app/views/home/top.html.erb
<div class="container">
  <div class="row">
      <div class="col-xs-8 offset-xs-2">
        <h1>Welcome to Coroぷり日記
        <i class="fas fa-book-open"></i>
        <i class="far fa-comment"></i>
        </h1>
      </div>
      <div class="col-xs-10 offset-xs-2 ">
      <div class="btn-group btn-group-lg" role="group">
        <p><%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg" %></p>
        
        <p><%= link_to "Sign in", new_user_session_path, class: "btn btn-success btn-lg" %></p>
      </div>
      </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Coroぷり日記</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/4254070997.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header>
    <nav class="navbar navbar-light" style="background-color: #FFCCCC">
      <div class="container">
        <div class="navbar-left mr-auto">
          <nav class="navbar-brand">
            Coroぷり日記
            <i class="fas fa-book-open"></i>
            <i class="far fa-comment"></i>
          </nav>
        </div>
        <div class="navbar">
            <ul class="navbar-nav">
            <%if user_signed_in? %>
              <li class="nav-item">
                <%= link_to 'Home', user_path(current_user.id) %>
              </li>
              <li class="nav-item">
                <%= link_to 'Coroぷりさん一覧', users_path, class: "" %>
              </li>
              <li class="nav-item">
                <%= link_to 'CoroDiaries一覧', blogs_path %>
              </li>
              <li class="nav-item">
                <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to "Coroぷり日記とは", home_about_path, class: "fas fa-link nav-link mr-3" %>
              </li>
              <li class="nav-item">
                <%= link_to "sign up", new_user_registration_path, class: "fas fa-edit nav-link mr-3" %>
              </li>
              <li class="nav-item">
                <%= link_to "login", new_user_session_path, class: "fas fa-sign-in-alt nav-link mr-3" %>
              </li>
            <% end %>
            </ul>
        </div>
        </div>
      </div>
    </nav>
    </header>
    <%= yield %>
  </body>
</html>

app/views/users/_profile.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-3">
      <%= link_to "New", new_blog_path, class: "fas fa-pencil-alt icon-4x" %>
    
      <table class="table">
        <tr>
          <th><%= attachment_image_tag user, :profile_image, size: "100x100", fallback: "noimage.png" %></th>
        </tr>
        <tr>
          <th>name</th>
          <th><%= user.name %></th>
        </tr>
        <tr>
          <th>introduction</th>
          <th><%= user.introduction %></th>
        </tr>
      </table>
      
      <%= link_to edit_user_path(user.id), class: "col-xs-12 btn btn-success"  do%>
        <i class="fas fa-user-edit"></i>
        プロフィール編集
      <% end %>
    
    </div> 

app/views/users/edit.html.erb
<h1>My page 編集</h1>
<%= form_with model:@user, local:true do |f| %>
  <h2>Name</h2>
  <%= f.text_field :name %>
  <h2>Image</h2>
  <%= f.attachment_field :profile_image %>
  <h2>Introdution</h2>
  <%= f.text_area :introduction %>
  <%= f.submit "編集する" %>
<% end %>

app/views/users/index.html.erb
<%= render 'users/profile', user: @user, blog: @blog %>
    <div class="col-xs-9">
      <h2>Coroぷりさん一覧</h2>
      <table class="table">
        <thead>
          <tr>
            <th>name</th>
            <th></th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= attachment_image_tag user, :profile_image, size: "50x50", fallback: "noimage.png" %></td>
              <td><%= user.name %></td>
              <td><%= link_to "Show", user_path(user) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<%= render 'users/profile', user: @user, blog: @blog %>
    <div class="col-xs-9">
      <h2>Coroぷりさん's ページ</h2>
        <h3><%= @user.name %></h3>
        <table class="table">
          <thead>
            <tr>
              <th>title</th>
            </tr>
          </thead>
          <tbody>
            <% @blogs.each do |blog| %>
              <tr>
                <td><%= link_to blog.title,blog, class: "blog_#{blog.id}" %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
    </div>
  </div>
</div>
<%= javascript_include_tag "loginalert.js" %>